import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Search,Plus,Upload,Users,Database,Archive,LogOut,ChevronRight,X,FileText,PanelRightClose,Save,History,Download,Trash2,Settings,ArrowLeft,Check,LockKeyhole,Library,BookMarked,RefreshCw,Eye,PenLine} from 'lucide-react';
import {api,configure,download,setToken,User,Lecture,Ref,Translation} from './api';
import './style.css';
import ScriptureManager from './ScriptureManager';
import Modal from './Modal';

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}

function Rendered({html,refs,onRef}:{html:string;refs:Ref[];onRef:(r:Ref)=>void}){return <div className="prose" onClick={e=>{const target=(e.target as HTMLElement).closest('[data-ref]');if(target){const ref=refs[Number(target.getAttribute('data-ref'))];if(ref)onRef(ref);}const link=(e.target as HTMLElement).closest('a');if(link){e.preventDefault();const href=link.getAttribute('href');if(href&&/^https?:\/\//.test(href))window.open(href,'_blank','noopener');}}} dangerouslySetInnerHTML={{__html:html}}/>}
function App(){
  const [status,setStatus]=useState<any>(null),[user,setUser]=useState<User|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [items,setItems]=useState<Lecture[]>([]),[lecture,setLecture]=useState<Lecture|null>(null),[query,setQuery]=useState(''),[trash,setTrash]=useState(false),[category,setCategory]=useState('');
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState({title:'',markdown:'',category:'',tags:''}),[preview,setPreview]=useState<{html:string;references:Ref[]}>({html:'',references:[]});
  const [modal,setModal]=useState(''),[pending,setPending]=useState<any>(null),[users,setUsers]=useState<User[]>([]),[translations,setTranslations]=useState<Translation[]>([]),[versions,setVersions]=useState<any[]>([]);
  const [reference,setReference]=useState<Ref|null>(null),[zh,setZh]=useState(''),[en,setEn]=useState(''),[verses,setVerses]=useState<any>({}),[verseError,setVerseError]=useState(''),[verseLoading,setVerseLoading]=useState(false);
  const [login,setLogin]=useState({username:'',password:'',display_name:''}),[connection,setConnection]=useState({host:'127.0.0.1',port:3307,username:'bible_library_app',password:'',database:'bible_library'});
  const [newUser,setNewUser]=useState({username:'',display_name:'',password:'',role:'reader'}),[password,setPassword]=useState({old_password:'',new_password:''}),[resetTarget,setResetTarget]=useState<User|null>(null),[resetValue,setResetValue]=useState('');
  const fileRef=useRef<HTMLInputElement>(null),scriptureRef=useRef<HTMLInputElement>(null),backupRef=useRef<HTMLInputElement>(null);
  const [scriptureDirty,setScriptureDirty]=useState(false),[scriptureBusy,setScriptureBusy]=useState(false);
  const dirty=scriptureDirty||editing&&!!lecture&&(draft.title!==lecture.title||draft.markdown!==lecture.markdown||draft.category!==lecture.category||draft.tags!==lecture.tags.join(', '));
  const admin=user?.role==='admin';
  const guard=()=>!dirty||window.confirm('正文有未保存的修改，确定放弃吗？');
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const loadStatus=async()=>setStatus(await api('/status'));
  const loadList=async()=>setItems(await api<Lecture[]>(`/lectures?q=${encodeURIComponent(query)}&trash=${trash}`));
  const loadTranslations=async()=>{const ts=await api<Translation[]>('/translations');setTranslations(ts);setZh(v=>ts.some(t=>String(t.id)===v)?v:String(ts.find(t=>t.language.toLowerCase().startsWith('zh'))?.id||''));setEn(v=>ts.some(t=>String(t.id)===v)?v:String(ts.find(t=>t.language.toLowerCase().startsWith('en'))?.id||''));};
  const acceptLecture=(l:Lecture)=>{setLecture(l);setDraft({title:l.title,markdown:l.markdown,category:l.category,tags:l.tags.join(', ')});setPreview({html:l.html,references:l.references});setReference(null);};
  const authenticate=(result:{token:string;user:User})=>{
    // Successful authentication also proves setup is complete, including the first administrator.
    setStatus((previous:any)=>({...previous,connected:true,initialized:true}));
    setToken(result.token);setUser(result.user);setLogin({username:'',password:'',display_name:''});setPassword({old_password:'',new_password:''});
  };
  useEffect(()=>{run(async()=>{await configure();await loadStatus();});const expire=()=>{setUser(null);setToken('');setLecture(null);setEditing(false);setModal('');setError('登录已失效，请重新登录。');};window.addEventListener('session-expired',expire);return()=>window.removeEventListener('session-expired',expire);},[]);
  useEffect(()=>{const off=window.desktop?.onClose(()=>{if(!scriptureBusy&&guard())window.desktop?.confirmClose();});const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{off?.();window.removeEventListener('beforeunload',before);};},[dirty,scriptureBusy]);
  useEffect(()=>window.desktop?.onBackendError(setError),[]);
  useEffect(()=>{if(user&&!user.must_change_password){run(async()=>{await loadList();await loadTranslations();});}},[user,query,trash]);
  useEffect(()=>{if(!editing)return;let canceled=false;const timer=setTimeout(()=>{api('/render','POST',{markdown:draft.markdown}).then(result=>{if(!canceled)setPreview(result);}).catch(e=>{if(!canceled)setError(e.message);});},300);return()=>{canceled=true;clearTimeout(timer);};},[draft.markdown,editing]);
  useEffect(()=>{let canceled=false;setVerses({});setVerseError('');if(!reference||reference.status!=='valid'){setVerseLoading(false);return;}setVerseLoading(true);const fetchVerse=async(id:string)=>id?api(`/verses?translation_id=${id}&book=${reference.book}&chapter=${reference.chapter}&start=${reference.start}&end=${reference.end}`):[];Promise.all([fetchVerse(zh),fetchVerse(en)]).then(([a,b])=>{if(!canceled)setVerses({zh:a,en:b});}).catch(e=>{if(!canceled)setVerseError(e.message);}).finally(()=>{if(!canceled)setVerseLoading(false);});return()=>{canceled=true;};},[reference,zh,en]);
  useEffect(()=>{if(notice){const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);}},[notice]);
  const openLecture=async(id:number)=>{if(!guard())return;await run(async()=>{acceptLecture(await api(`/lectures/${id}`));setEditing(false);});};
  const save=()=>run(async()=>{if(!lecture)return;const l=await api<Lecture>(`/lectures/${lecture.id}`,'PUT',{...draft,tags:draft.tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean),revision:lecture.revision});acceptLecture(l);await loadList();setNotice('讲义已保存，历史版本已记录');});
  const openModal=(name:string)=>run(async()=>{if(!guard())return;if(lecture)acceptLecture(lecture);setEditing(false);setPending(null);if(name==='users')setUsers(await api('/users'));if(name==='history'&&lecture)setVersions(await api(`/lectures/${lecture.id}/history`));setModal(name);});
  const importLecture=(file?:File)=>{if(!file)return;run(async()=>{if(!guard())return;const form=new FormData();form.append('file',file);setPending(await api('/imports/preview','POST',form));setModal('import');});};
  const importScripture=(file?:File)=>{if(!file)return;run(async()=>{const text=await file.text();if(text.length>20_000_000)throw Error('经文数据过大，请拆分');let parsed;try{parsed=JSON.parse(text);}catch{throw Error('请选择有效的 JSON 经文文件');}setPending(await api('/translations/preview','POST',parsed));setModal('scripture-preview');});};
  const importBackup=(file?:File)=>{if(!file)return;run(async()=>{const form=new FormData();form.append('file',file);setPending(await api('/backups/preview','POST',form));setModal('restore');});};
  const allCategories=Array.from(new Set(items.map(i=>i.category).filter(Boolean)));
  const visibleItems=category?items.filter(i=>i.category===category):items;
  return <>
    {error&&<div className="toast error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}{notice&&<div className="toast success" role="status"><Check size={18}/>{notice}</div>}
    {busy&&<div className="busy-line"/>}
    {!user?<div className="welcome"><div className="welcome-copy"><span className="brand-mark"><BookOpen size={28}/></span><p className="eyebrow">SCRIPTURE LIBRARY</p><h1>让每一份讲义，<br/>与经文相连。</h1><p>收藏、整理与研读。<br/>属于你的本地圣经讲义资料库。</p><div className="local-badge"><span/> 资料库 · 经文对照</div></div><div className="welcome-form">
      {!status?<><h2>正在连接资料库</h2><p className="muted">启动本地服务，检查数据库状态。</p><button onClick={()=>run(async()=>{await configure();await loadStatus();})}>重新连接</button></>:!status.connected?<form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/connection','POST',connection);await loadStatus();});}}><p className="eyebrow">FIRST STEPS / 01</p><h2>连接资料库数据库</h2><p className="muted">请先安装 MySQL，并创建一个空数据库。连接信息仅保存在本机。</p>{status.error&&<p className="callout">{status.error}</p>}<Field label="数据库名称"><input required value={connection.database} onChange={e=>setConnection({...connection,database:e.target.value})}/></Field><div className="row"><Field label="主机"><input value={connection.host} onChange={e=>setConnection({...connection,host:e.target.value})}/></Field><Field label="端口"><input type="number" value={connection.port} onChange={e=>setConnection({...connection,port:Number(e.target.value)})}/></Field></div><Field label="数据库用户名"><input required value={connection.username} onChange={e=>setConnection({...connection,username:e.target.value})}/></Field><Field label="数据库密码"><input type="password" value={connection.password} onChange={e=>setConnection({...connection,password:e.target.value})}/></Field><button className="primary full" disabled={busy}>检测连接并继续 <ChevronRight size={17}/></button></form>:<form onSubmit={e=>{e.preventDefault();run(async()=>{authenticate(await api(status.initialized?'/login':'/setup','POST',login));});}}><p className="eyebrow">{status.initialized?'WELCOME BACK':'FIRST STEPS / 02'}</p><h2>{status.initialized?'登录讲义资料库':'创建管理员账户'}</h2><p className="muted">{status.initialized?'用你的账户，继续阅读与研习。':'管理员可以维护讲义、导入经文和添加阅读用户。'}</p><Field label="用户名（1～80 个字符）"><input autoComplete="username" pattern="[A-Za-z0-9_.\-]{1,80}" maxLength={80} title="1～80 个字符，仅限英文字母、数字、下划线、点和短横线" required value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} placeholder="英文字母、数字、下划线、点、短横线"/></Field>{!status.initialized&&<Field label="显示名称"><input required value={login.display_name} onChange={e=>setLogin({...login,display_name:e.target.value})}/></Field>}<Field label="密码"><input type="password" autoComplete={status.initialized?'current-password':'new-password'} minLength={status.initialized?1:6} maxLength={128} required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder={status.initialized?'输入你的密码':'至少 6 个字符'}/></Field><button className="primary full" disabled={busy}>{status.initialized?'登录':'创建并进入'} <ChevronRight size={17}/></button><p className="small muted">{status.initialized?'没有账户？请联系资料库管理员。':'账户密码与 MySQL 连接密码相互独立。'}</p></form>}
    </div></div>:user.must_change_password?<div className="password-screen"><form className="card" onSubmit={e=>{e.preventDefault();run(async()=>authenticate(await api('/password','POST',password)));}}><LockKeyhole size={28}/><h2>设置你的新密码</h2><p className="muted">首次登录或密码重置后，需要修改初始密码才能查看资料。</p><Field label="当前初始密码"><input required type="password" value={password.old_password} onChange={e=>setPassword({...password,old_password:e.target.value})}/></Field><Field label="新密码（至少 6 个字符）"><input required type="password" minLength={6} maxLength={128} value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/></Field><button className="primary full" disabled={busy}>修改密码并进入</button><button className="full" type="button" onClick={()=>{setUser(null);setToken('');}}>返回登录</button></form></div>:<div className="workspace">
      <aside className="sidebar"><div className="brand"><BookOpen size={25}/><div>圣经讲义<small>SCRIPTURE LIBRARY</small></div></div><div className="nav-label">我的资料库</div><button className={'nav '+(!trash?'active':'')} onClick={()=>{if(guard()){setTrash(false);setCategory('');setEditing(false);setLecture(null);}}}><Library size={18}/>全部讲义 <span>{!trash?items.length:''}</span></button><div className="nav-label space">分类</div><button className={'nav sub '+(!category?'selected':'')} onClick={()=>setCategory('')}>全部分类</button>{allCategories.map(c=><button className={'nav sub '+(category===c?'selected':'')} key={c} onClick={()=>setCategory(c)}>{c}</button>)}{!allCategories.length&&<p className="side-hint">整理讲义时添加分类</p>}<div className="sidebar-bottom">{admin&&<><div className="nav-label">管理</div><button className="nav" onClick={()=>openModal('users')}><Users size={18}/>用户管理</button><button className="nav" onClick={()=>openModal('scripture')}><Database size={18}/>经文数据</button><button className={'nav '+(trash?'active':'')} onClick={()=>{if(guard()){setTrash(true);setCategory('');setLecture(null);setEditing(false);}}}><Trash2 size={18}/>回收站</button><button className="nav" onClick={()=>openModal('backup')}><Archive size={18}/>备份与恢复</button></>}<div className="profile"><span className="avatar">{user.display_name.slice(0,1)}</span><div><strong>{user.display_name}</strong><small>{admin?'管理员':'阅读用户'}</small></div><button className="icon" aria-label="账户设置" onClick={()=>openModal('account')}><Settings size={17}/></button></div><div className="offline"><span/> 本机资料库</div></div></aside>
      <section className="library-column"><header><p className="eyebrow">YOUR COLLECTION</p><h1>{trash?'回收站':'讲义资料库'}</h1><p className="muted small">{trash?'恢复后需重新发布':'在文字中研读，在经文中思想'}</p></header><div className="search"><Search size={17}/><input aria-label="搜索讲义" placeholder="搜索标题或正文…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon" onClick={()=>setQuery('')}><X size={14}/></button>}</div>{admin&&!trash&&<div className="collection-actions"><button className="primary" disabled={busy} onClick={()=>{if(guard())fileRef.current?.click();}}><Upload size={15}/>导入讲义</button><button title="新建 Markdown 讲义" aria-label="新建讲义" disabled={busy} onClick={()=>run(async()=>{if(!guard())return;const l=await api<Lecture>('/lectures','POST',{title:'未命名讲义',markdown:'# 未命名讲义\n\n在这里开始写作。',category:'',tags:[]});acceptLecture(l);setEditing(true);await loadList();})}><Plus size={18}/></button></div>}<div className="list-caption">{category||'全部讲义'}<span>{visibleItems.length} 篇</span></div><div className="lecture-list">{visibleItems.map(item=><button className={'lecture-card '+(lecture?.id===item.id?'chosen':'')} key={item.id} onClick={()=>openLecture(item.id)}><div className="lecture-card-top"><BookMarked size={17}/><span>{item.category||'未分类'}</span>{admin&&<i className={item.published?'published':''}>{item.published?'已发布':'未发布'}</i>}</div><h3>{item.title}</h3><div className="lecture-card-meta"><span>{new Date(item.updated_at+'Z').toLocaleDateString('zh-CN')}</span><ChevronRight size={15}/></div></button>)}{!visibleItems.length&&<div className="list-empty"><FileText size={26}/><p>{query?'没有找到相关讲义':trash?'回收站是空的':'还没有可阅读的讲义'}</p><small>{admin&&!trash?'导入 Word，开始整理第一篇讲义。':'已发布的讲义会显示在这里。'}</small></div>}</div><footer className="column-footer">{admin?'支持 Word · Markdown':'只显示已发布讲义'}</footer></section>
      <main className={'reading '+(editing?'is-editing':'')}>{lecture?<><header className="reading-toolbar"><span><FileText size={16}/> {editing?'编辑讲义':'阅读讲义'}</span><div>{admin&&!lecture.deleted&&<>{editing?<><button onClick={()=>{if(guard()){acceptLecture(lecture);setEditing(false);}}}><Eye size={15}/>阅读</button><button className="primary" disabled={busy||!dirty} onClick={save}><Save size={15}/>保存</button></>:<button onClick={()=>setEditing(true)}><PenLine size={15}/>编辑</button>}<button title="历史版本" aria-label="历史版本" onClick={()=>openModal('history')}><History size={16}/></button><button title="导出 Markdown" aria-label="导出 Markdown" onClick={()=>run(async()=>{if(await download(`/lectures/${lecture.id}/export`,`${lecture.title}.md`))setNotice('Markdown 已导出');})}><Download size={16}/></button></>}{admin&&<button title="讲义操作" onClick={()=>openModal('lecture-actions')}>管理</button>}</div></header>{editing?<div className="editor-shell"><div className="editor-metadata"><input className="title-input" aria-label="讲义标题" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><div className="row"><input placeholder="分类" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><input placeholder="标签，用逗号分隔" value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></div></div><div className="editor-columns"><div><div className="editor-label">MARKDOWN {dirty&&<span>未保存</span>}</div><textarea spellCheck={false} aria-label="Markdown 正文" value={draft.markdown} onChange={e=>setDraft({...draft,markdown:e.target.value})}/></div><div className="live-preview"><div className="editor-label">实时预览</div><Rendered html={preview.html} refs={preview.references} onRef={setReference}/></div></div></div>:<article className="article"><div className="article-meta"><span>{lecture.category||'讲义'}</span><span>·</span><span>{new Date(lecture.updated_at+'Z').toLocaleDateString('zh-CN')}</span>{admin&&<span className="status-pill">{lecture.published?'已发布':'未发布'}</span>}</div><h1>{lecture.title}</h1><div className="tags">{lecture.tags.map(t=><span key={t}>#{t}</span>)}</div>{lecture.references?.length>0&&<div className="reference-hint"><BookOpen size={15}/>点击正文中的经文引用，查看中英文对照</div>}<Rendered html={lecture.html} refs={lecture.references||[]} onRef={setReference}/><div className="article-end">◇</div></article>}</>:<div className="empty-reading"><div className="book-orbit"><BookOpen size={42} strokeWidth={1.2}/></div><p className="eyebrow">READ · REFLECT · CONNECT</p><h2>从一篇讲义开始</h2><p>选择左侧讲义，安静阅读。<br/>点击经文引用，在这里连接更完整的上下文。</p>{admin&&<button onClick={()=>fileRef.current?.click()}><Upload size={16}/>导入第一份讲义</button>}</div>}</main>
      {reference&&<aside className="scripture-drawer"><header><div><p className="eyebrow">SCRIPTURE</p><h2>{reference.raw}</h2></div><button className="icon" aria-label="关闭经文" onClick={()=>setReference(null)}><PanelRightClose size={20}/></button></header>{reference.status!=='valid'?<p className="callout">{reference.message}</p>:<><p className="drawer-intro">经文对照 {reference.part&&'· 半节标记按完整经节显示'}</p><Field label="中文译本"><select value={zh} onChange={e=>setZh(e.target.value)}><option value="">选择中文译本</option>{translations.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="英文译本"><select value={en} onChange={e=>setEn(e.target.value)}><option value="">选择英文译本</option>{translations.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>{!translations.length&&<p className="callout">资料库尚未导入经文。{admin?'请在「经文数据」中维护译本正文。':'请联系管理员维护译本正文。'}</p>}{verseLoading&&<p className="muted">正在读取经文…</p>}{verseError&&<p className="callout">{verseError}</p>}<div className="verse-list">{!verseLoading&&!verseError&&Array.from({length:reference.end!-reference.start!+1},(_,i)=>{const n=reference.start!+i;return <section key={n}><span className="verse-number">{String(n).padStart(2,'0')}</span><p>{zh?(verses.zh?.[i]?.text||'此译本缺少该节经文'):'尚未选择中文译本'}</p><p className="english">{en?(verses.en?.[i]?.text||'此译本缺少该节经文'):'尚未选择英文译本'}</p></section>;})}</div><p className="small muted">按卷、章、节对照；译本分节差异不自动校正。</p></>}</aside>}
    </div>}
    <input ref={fileRef} type="file" hidden accept=".docx,.md" onChange={e=>{importLecture(e.target.files?.[0]);e.target.value='';}}/><input ref={scriptureRef} type="file" hidden accept=".json" onChange={e=>{importScripture(e.target.files?.[0]);e.target.value='';}}/><input ref={backupRef} type="file" hidden accept=".zip" onChange={e=>{importBackup(e.target.files?.[0]);e.target.value='';}}/>
    {modal&&<Modal title={({users:'用户管理',account:'账户设置',import:'确认导入讲义',history:'历史版本',scripture:'经文数据', 'scripture-preview':'确认译本差异',backup:'备份与恢复',restore:'确认恢复备份','lecture-actions':'讲义管理'} as Record<string,string>)[modal]||'管理'} onClose={()=>{if(!busy&&!scriptureBusy&&(!scriptureDirty||window.confirm('经文管理有未保存的内容，确定放弃吗？')))setModal('');}} wide={['import','users','history','scripture','scripture-preview'].includes(modal)}>
      {modal==='users'&&<><p className="muted">管理员维护资料，阅读用户查看全部已发布讲义。</p><div className="user-list">{users.map(u=><div className="user-row" key={u.id}><span className="avatar">{u.display_name.slice(0,1)}</span><div><strong>{u.display_name}</strong><small>{u.username} · {u.role==='admin'?'管理员':'阅读用户'} · {u.active?'启用':'停用'}{u.must_change_password?' · 待修改密码':''}</small></div><button disabled={busy} onClick={()=>{setResetTarget(u);setResetValue('');}}>重置密码</button><button disabled={busy} onClick={()=>run(async()=>{await api(`/users/${u.id}`,'PATCH',{active:!u.active});if(u.id===user?.id){setUser(null);setToken('');setModal('');return;}setUsers(await api('/users'));})}>{u.active?'停用':'启用'}</button></div>)}</div>{resetTarget&&<form className="inset" onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/users/${resetTarget.id}/reset-password`,'POST',{password:resetValue});setResetTarget(null);setResetValue('');if(resetTarget.id===user?.id){setUser(null);setToken('');setModal('');}else setUsers(await api('/users'));setNotice('密码已重置，旧会话已失效');});}}><Field label={`为 ${resetTarget.display_name} 设置新初始密码（至少 6 位）`}><input type="password" required minLength={6} maxLength={128} value={resetValue} onChange={e=>setResetValue(e.target.value)}/></Field><button disabled={busy} className="primary">确认重置</button></form>}<form className="inset" onSubmit={e=>{e.preventDefault();run(async()=>{await api('/users','POST',newUser);setUsers(await api('/users'));setNewUser({username:'',display_name:'',password:'',role:'reader'});setNotice('用户已添加，首次登录需修改密码');});}}><h3>添加用户</h3><div className="row"><Field label="用户名（1～80 个字符）"><input required pattern="[A-Za-z0-9_.\-]{1,80}" maxLength={80} title="1～80 个字符，仅限英文字母、数字、下划线、点和短横线" placeholder="英文字母、数字、下划线、点、短横线" value={newUser.username} onChange={e=>setNewUser({...newUser,username:e.target.value})}/><small className="muted">大小写不区分，用户名不可重复。</small></Field><Field label="显示名称"><input required value={newUser.display_name} onChange={e=>setNewUser({...newUser,display_name:e.target.value})}/></Field></div><div className="row"><Field label="初始密码（至少 6 位）"><input type="password" required minLength={6} maxLength={128} value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/></Field><Field label="角色"><select value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}><option value="reader">阅读用户</option><option value="admin">管理员</option></select></Field></div><button className="primary" disabled={busy}><Plus size={16}/>添加用户</button></form></>}
      {modal==='account'&&<><p>{user?.display_name} <span className="muted">@{user?.username}</span></p><form onSubmit={e=>{e.preventDefault();run(async()=>{authenticate(await api('/password','POST',password));setModal('');setNotice('密码已修改');});}}><Field label="当前密码"><input required type="password" value={password.old_password} onChange={e=>setPassword({...password,old_password:e.target.value})}/></Field><Field label="新密码（至少 6 位）"><input required type="password" minLength={6} maxLength={128} value={password.new_password} onChange={e=>setPassword({...password,new_password:e.target.value})}/></Field><button disabled={busy} className="primary">修改密码</button></form><hr/><button disabled={busy} onClick={()=>run(async()=>{await api('/logout','POST');setUser(null);setToken('');setLecture(null);setModal('');setItems([]);})}><LogOut size={16}/>退出登录</button></>}
      {modal==='import'&&pending&&<><Field label="讲义标题"><input value={pending.title} onChange={e=>setPending({...pending,title:e.target.value})}/></Field>{pending.warnings.length?pending.warnings.map((w:string,i:number)=><p className="callout" key={i}>{w}</p>):<p className="callout neutral">转换完成。请核对正文内容与顺序，原始文件将一并保留。</p>}<div className="preview-box"><Rendered html={pending.html} refs={pending.references} onRef={()=>{}}/></div><div className="modal-actions"><button onClick={()=>setModal('')}>取消</button><button className="primary" disabled={busy||!pending.title.trim()} onClick={()=>run(async()=>{const l=await api<Lecture>('/imports/confirm','POST',{preview_id:pending.preview_id,title:pending.title});acceptLecture(l);setEditing(false);setTrash(false);setCategory('');setModal('');await loadList();setNotice('已导入为未发布讲义');})}>已核对，确认导入</button></div></>}
      {modal==='history'&&lecture&&<><p className="muted">恢复会创建新版本，当前内容仍保留在历史中。</p>{versions.map(v=><details className="history-row" key={v.id}><summary>版本 {v.revision} · {new Date(v.created_at+'Z').toLocaleString('zh-CN')} <span>{v.title}</span></summary><pre>{v.markdown}</pre><button disabled={busy||v.revision===lecture.revision} onClick={()=>run(async()=>{if(!window.confirm(`恢复到版本 ${v.revision}？`))return;acceptLecture(await api(`/lectures/${lecture.id}/history/${v.id}/restore`,'POST'));setModal('');await loadList();setNotice('已恢复为一个新版本');})}>恢复此版本</button></details>)}</>}
      {modal==='lecture-actions'&&lecture&&<><h3>{lecture.title}</h3>{lecture.deleted?<button className="primary" disabled={busy} onClick={()=>run(async()=>{await api(`/lectures/${lecture.id}/trash`,'PATCH',{deleted:false});setLecture(null);setModal('');await loadList();setNotice('已恢复到资料库，当前为未发布状态');})}><RefreshCw size={16}/>恢复讲义</button>:<div className="action-stack"><button className="primary" disabled={busy} onClick={()=>run(async()=>{acceptLecture(await api(`/lectures/${lecture.id}/publish`,'PATCH',{published:!lecture.published}));setModal('');await loadList();setNotice(lecture.published?'已取消发布':'已发布，阅读用户现在可以查看');})}>{lecture.published?'取消发布':'发布给全部阅读用户'}</button><button className="danger" disabled={busy} onClick={()=>run(async()=>{if(!window.confirm('将讲义移入回收站并停止发布？'))return;await api(`/lectures/${lecture.id}/trash`,'PATCH',{deleted:true});setLecture(null);setModal('');await loadList();})}><Trash2 size={16}/>移入回收站</button></div>}{lecture.has_original&&<button className="spaced" onClick={()=>run(async()=>{await download(`/lectures/${lecture.id}/original`,'original'+lecture.original_extension);})}><Download size={16}/>下载原始文件</button>}{lecture.import_report?.map((w,i)=><p className="callout" key={i}>{w}</p>)}</>}
      {modal==='scripture'&&<ScriptureManager translations={translations} onRefresh={loadTranslations} onDirty={setScriptureDirty} onBusy={setScriptureBusy}/>}
      {modal==='scripture-preview'&&pending&&<><p>共 {pending.count} 节；新增 {pending.summary.added}，修改 {pending.summary.changed}，删除 {pending.summary.removed}。</p>{pending.warnings.map((w:string,i:number)=><p className="callout" key={i}>{w}</p>)}<div className="diff-list">{pending.changes.map((c:any,i:number)=><details key={i}><summary>{c.book} {c.chapter}:{c.verse} · {{added:'新增',changed:'修改',removed:'删除'}[c.kind as string]}</summary>{c.before&&<p className="diff-before">原文：{c.before}</p>}{c.after&&<p>导入：{c.after}</p>}</details>)}</div><button className="primary spaced" disabled={busy} onClick={()=>run(async()=>{await api('/translations/confirm','POST',{preview_id:pending.preview_id});await loadTranslations();setModal('scripture');setPending(null);setNotice('译本已导入');})}>确认{pending.existing?'替换译本':'导入译本'}</button></>}
      {modal==='backup'&&<><p className="muted">完整备份包含账户、讲义、历史、经文和原始文件。数据库连接密码不包含在备份中。</p><div className="action-stack"><button className="primary" disabled={busy} onClick={()=>run(async()=>{if(await download('/backups',`圣经讲义备份-${new Date().toISOString().slice(0,10)}.zip`))setNotice('完整备份已保存');})}><Download size={17}/>导出完整备份</button><button disabled={busy} onClick={()=>backupRef.current?.click()}><Archive size={17}/>选择备份并预览恢复</button></div><p className="small muted">恢复前自动生成安全备份；恢复后所有账户重新登录。</p></>}
      {modal==='restore'&&pending&&<><p className="callout">{pending.warning}</p><p>备份时间：{pending.created_at}</p><p>用户 {pending.counts.users} 个 · 讲义 {pending.counts.lectures} 篇 · 经文 {pending.counts.verses} 节</p><button className="danger" disabled={busy} onClick={()=>run(async()=>{if(!window.confirm('确认用此备份替换当前资料及账户？'))return;const result=await api('/backups/restore','POST',{preview_id:pending.preview_id});setToken('');setUser(null);setLecture(null);setItems([]);setModal('');await loadStatus();setNotice(result.message);})}>备份当前资料并恢复</button></>}
    </Modal>}
  </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
